language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    update: true
before_install:
  - export COVID_KEY=sekret
install:
  - pip install pip -U
  - pip install -r requirements-dev.txt -U
script:
    - ./analyse-source-code.sh
after_success:
  - coveralls
notifications:
  email: false
